/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface EmergencyProfile {
  'accessCode' : string,
  'healthConditions' : string,
  'nextOfKin' : string,
}
export type ExternalBlob = Uint8Array;
export interface Place {
  'name' : string,
  'submittedBy' : Principal,
  'description' : string,
  'category' : PlaceCategory,
  'location' : string,
}
export type PlaceCategory = { 'gasStation' : null } |
  { 'hotel' : null } |
  { 'shop' : null } |
  { 'mechanic' : null } |
  { 'restaurant' : null };
export interface Route {
  'creator' : Principal,
  'destination' : string,
  'waypoints' : Array<string>,
  'start' : string,
  'notes' : [] | [string],
  'dateTime' : Time,
}
export interface SOSSnapshot {
  'latitude' : number,
  'user' : Principal,
  'longitude' : number,
  'timestamp' : Time,
}
export type Time = bigint;
export interface UserProfile {
  'licenseProof' : [] | [ExternalBlob],
  'name' : string,
  'idProof' : [] | [ExternalBlob],
  'isVerified' : boolean,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addPlace' : ActorMethod<[string, PlaceCategory, string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOrUpdateEmergencyProfile' : ActorMethod<
    [string, string, string],
    undefined
  >,
  'createRoute' : ActorMethod<
    [string, string, Array<string>, Time, [] | [string]],
    undefined
  >,
  'createSOSSnapshot' : ActorMethod<[number, number], undefined>,
  'createUserProfile' : ActorMethod<[string], undefined>,
  'emergencyLookup' : ActorMethod<
    [Principal, string],
    {
      'sosSnapshot' : [] | [SOSSnapshot],
      'emergencyProfile' : [] | [EmergencyProfile],
    }
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getRoutes' : ActorMethod<[Principal], Array<Route>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'reviewVerification' : ActorMethod<[Principal, boolean], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchPlaces' : ActorMethod<[[] | [PlaceCategory]], Array<Place>>,
  'uploadVerification' : ActorMethod<
    [[] | [ExternalBlob], [] | [ExternalBlob]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];