/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const PlaceCategory = IDL.Variant({
  'gasStation' : IDL.Null,
  'hotel' : IDL.Null,
  'shop' : IDL.Null,
  'mechanic' : IDL.Null,
  'restaurant' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const SOSSnapshot = IDL.Record({
  'latitude' : IDL.Float64,
  'user' : IDL.Principal,
  'longitude' : IDL.Float64,
  'timestamp' : Time,
});
export const EmergencyProfile = IDL.Record({
  'accessCode' : IDL.Text,
  'healthConditions' : IDL.Text,
  'nextOfKin' : IDL.Text,
});
export const EmergencyLookupResult = IDL.Record({
  'sosSnapshot' : IDL.Opt(SOSSnapshot),
  'userName' : IDL.Opt(IDL.Text),
  'emergencyProfile' : IDL.Opt(EmergencyProfile),
});
export const MeetupLocation = IDL.Record({
  'latitude' : IDL.Float64,
  'name' : IDL.Text,
  'user' : IDL.Principal,
  'isActive' : IDL.Bool,
  'longitude' : IDL.Float64,
  'timestamp' : Time,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserProfile = IDL.Record({
  'licenseProof' : IDL.Opt(ExternalBlob),
  'name' : IDL.Text,
  'idProof' : IDL.Opt(ExternalBlob),
  'isVerified' : IDL.Bool,
});
export const Route = IDL.Record({
  'creator' : IDL.Principal,
  'destination' : IDL.Text,
  'waypoints' : IDL.Vec(IDL.Text),
  'start' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'dateTime' : Time,
});
export const Place = IDL.Record({
  'name' : IDL.Text,
  'submittedBy' : IDL.Principal,
  'description' : IDL.Text,
  'category' : PlaceCategory,
  'location' : IDL.Text,
});
export const MeetupLocationInput = IDL.Record({
  'latitude' : IDL.Float64,
  'name' : IDL.Text,
  'longitude' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addPlace' : IDL.Func([IDL.Text, PlaceCategory, IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOrUpdateEmergencyProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'createRoute' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), Time, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'createSOSSnapshot' : IDL.Func([IDL.Float64, IDL.Float64], [], []),
  'createUserProfile' : IDL.Func([IDL.Text], [], []),
  'deactivateMeetupLocation' : IDL.Func([], [], []),
  'emergencyLookup' : IDL.Func(
      [IDL.Principal, IDL.Text],
      [EmergencyLookupResult],
      ['query'],
    ),
  'getAllActiveMeetupLocations' : IDL.Func(
      [],
      [IDL.Vec(MeetupLocation)],
      ['query'],
    ),
  'getAllAvailableMeetupLocations' : IDL.Func(
      [],
      [IDL.Vec(MeetupLocation)],
      ['query'],
    ),
  'getAllLatestSOSLocations' : IDL.Func([], [IDL.Vec(SOSSnapshot)], ['query']),
  'getAllUserProfiles' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLatestMeetupLocation' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(MeetupLocation)],
      ['query'],
    ),
  'getLatestSOSLocation' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(SOSSnapshot)],
      ['query'],
    ),
  'getMeetupLocation' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(MeetupLocation)],
      ['query'],
    ),
  'getRoutes' : IDL.Func([IDL.Principal], [IDL.Vec(Route)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'requestAdminAccess' : IDL.Func([], [], []),
  'reviewVerification' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchPlaces' : IDL.Func(
      [IDL.Opt(PlaceCategory)],
      [IDL.Vec(Place)],
      ['query'],
    ),
  'shareMeetupLocation' : IDL.Func([MeetupLocationInput], [], []),
  'updateMeetupLocation' : IDL.Func([MeetupLocationInput], [], []),
  'uploadVerification' : IDL.Func(
      [IDL.Opt(ExternalBlob), IDL.Opt(ExternalBlob)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const PlaceCategory = IDL.Variant({
    'gasStation' : IDL.Null,
    'hotel' : IDL.Null,
    'shop' : IDL.Null,
    'mechanic' : IDL.Null,
    'restaurant' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const SOSSnapshot = IDL.Record({
    'latitude' : IDL.Float64,
    'user' : IDL.Principal,
    'longitude' : IDL.Float64,
    'timestamp' : Time,
  });
  const EmergencyProfile = IDL.Record({
    'accessCode' : IDL.Text,
    'healthConditions' : IDL.Text,
    'nextOfKin' : IDL.Text,
  });
  const EmergencyLookupResult = IDL.Record({
    'sosSnapshot' : IDL.Opt(SOSSnapshot),
    'userName' : IDL.Opt(IDL.Text),
    'emergencyProfile' : IDL.Opt(EmergencyProfile),
  });
  const MeetupLocation = IDL.Record({
    'latitude' : IDL.Float64,
    'name' : IDL.Text,
    'user' : IDL.Principal,
    'isActive' : IDL.Bool,
    'longitude' : IDL.Float64,
    'timestamp' : Time,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserProfile = IDL.Record({
    'licenseProof' : IDL.Opt(ExternalBlob),
    'name' : IDL.Text,
    'idProof' : IDL.Opt(ExternalBlob),
    'isVerified' : IDL.Bool,
  });
  const Route = IDL.Record({
    'creator' : IDL.Principal,
    'destination' : IDL.Text,
    'waypoints' : IDL.Vec(IDL.Text),
    'start' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'dateTime' : Time,
  });
  const Place = IDL.Record({
    'name' : IDL.Text,
    'submittedBy' : IDL.Principal,
    'description' : IDL.Text,
    'category' : PlaceCategory,
    'location' : IDL.Text,
  });
  const MeetupLocationInput = IDL.Record({
    'latitude' : IDL.Float64,
    'name' : IDL.Text,
    'longitude' : IDL.Float64,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addPlace' : IDL.Func(
        [IDL.Text, PlaceCategory, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOrUpdateEmergencyProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'createRoute' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), Time, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'createSOSSnapshot' : IDL.Func([IDL.Float64, IDL.Float64], [], []),
    'createUserProfile' : IDL.Func([IDL.Text], [], []),
    'deactivateMeetupLocation' : IDL.Func([], [], []),
    'emergencyLookup' : IDL.Func(
        [IDL.Principal, IDL.Text],
        [EmergencyLookupResult],
        ['query'],
      ),
    'getAllActiveMeetupLocations' : IDL.Func(
        [],
        [IDL.Vec(MeetupLocation)],
        ['query'],
      ),
    'getAllAvailableMeetupLocations' : IDL.Func(
        [],
        [IDL.Vec(MeetupLocation)],
        ['query'],
      ),
    'getAllLatestSOSLocations' : IDL.Func(
        [],
        [IDL.Vec(SOSSnapshot)],
        ['query'],
      ),
    'getAllUserProfiles' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLatestMeetupLocation' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(MeetupLocation)],
        ['query'],
      ),
    'getLatestSOSLocation' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(SOSSnapshot)],
        ['query'],
      ),
    'getMeetupLocation' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(MeetupLocation)],
        ['query'],
      ),
    'getRoutes' : IDL.Func([IDL.Principal], [IDL.Vec(Route)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'requestAdminAccess' : IDL.Func([], [], []),
    'reviewVerification' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchPlaces' : IDL.Func(
        [IDL.Opt(PlaceCategory)],
        [IDL.Vec(Place)],
        ['query'],
      ),
    'shareMeetupLocation' : IDL.Func([MeetupLocationInput], [], []),
    'updateMeetupLocation' : IDL.Func([MeetupLocationInput], [], []),
    'uploadVerification' : IDL.Func(
        [IDL.Opt(ExternalBlob), IDL.Opt(ExternalBlob)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };