/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface MeetupLocationInput {
    latitude: number;
    name: string;
    longitude: number;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface EmergencyProfile {
    accessCode: string;
    healthConditions: string;
    nextOfKin: string;
}
export type Time = bigint;
export interface MemberSummary {
    userId: Principal;
    name: string;
    isVerified: boolean;
    registrationTime: Time;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface EmergencyLookupResult {
    sosSnapshot?: SOSSnapshot;
    userName?: string;
    emergencyProfile?: EmergencyProfile;
}
export interface SOSSnapshot {
    latitude: number;
    user: Principal;
    longitude: number;
    timestamp: Time;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface ActivityLogEntry {
    description: string;
    timestamp: Time;
    initiatedBy: Principal;
    eventType: EventType;
}
export interface Place {
    name: string;
    submittedBy: Principal;
    description: string;
    category: PlaceCategory;
    location: string;
}
export interface MeetupLocation {
    latitude: number;
    name: string;
    user: Principal;
    isActive: boolean;
    longitude: number;
    timestamp: Time;
}
export interface UserAccountDetails {
    recentRoutes: Array<Route>;
    emergencyProfile?: EmergencyProfile;
    accountCreated: Time;
    activityLog: Array<ActivityLogEntry>;
    placesAdded: Array<Place>;
    lastLocations: Array<MeetupLocation>;
    profile: UserProfile;
}
export interface UserProfile {
    licenseProof?: ExternalBlob;
    name: string;
    idProof?: ExternalBlob;
    isVerified: boolean;
    registrationTime: Time;
}
export interface Route {
    creator: Principal;
    destination: string;
    waypoints: Array<string>;
    start: string;
    notes?: string;
    dateTime: Time;
}
export enum EventType {
    sosSnapshot = "sosSnapshot",
    routeCreated = "routeCreated",
    meetupLocationUpdated = "meetupLocationUpdated",
    verificationSubmitted = "verificationSubmitted",
    meetupLocationShared = "meetupLocationShared",
    adminAction = "adminAction",
    emergencyProfileUpdated = "emergencyProfileUpdated",
    verificationReviewed = "verificationReviewed",
    userRegistration = "userRegistration",
    placeAdded = "placeAdded"
}
export enum PlaceCategory {
    gasStation = "gasStation",
    hotel = "hotel",
    shop = "shop",
    mechanic = "mechanic",
    restaurant = "restaurant"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addPlace(name: string, category: PlaceCategory, description: string, location: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createOrUpdateEmergencyProfile(nextOfKin: string, healthConditions: string, accessCode: string): Promise<void>;
    createRoute(start: string, destination: string, waypoints: Array<string>, dateTime: Time, notes: string | null): Promise<void>;
    createSOSSnapshot(latitude: number, longitude: number): Promise<void>;
    deactivateMeetupLocation(): Promise<void>;
    emergencyLookup(user: Principal, accessCode: string): Promise<EmergencyLookupResult>;
    getActivityLogs(): Promise<Array<ActivityLogEntry>>;
    getAllActiveMeetupLocations(): Promise<Array<MeetupLocation>>;
    getAllAvailableMeetupLocations(): Promise<Array<MeetupLocation>>;
    getAllLatestSOSLocations(): Promise<Array<SOSSnapshot>>;
    getAllMembers(): Promise<Array<MemberSummary>>;
    getAllUserProfiles(): Promise<Array<[Principal, UserProfile]>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getLatestMeetupLocation(user: Principal): Promise<MeetupLocation | null>;
    getLatestSOSLocation(user: Principal): Promise<SOSSnapshot | null>;
    getMeetupLocation(user: Principal): Promise<MeetupLocation | null>;
    getRoutes(user: Principal): Promise<Array<Route>>;
    getUserAccountDetails(userId: Principal): Promise<UserAccountDetails>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    reviewVerification(user: Principal, approved: boolean): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchPlaces(category: PlaceCategory | null): Promise<Array<Place>>;
    shareMeetupLocation(locationInput: MeetupLocationInput): Promise<void>;
    updateMeetupLocation(locationInput: MeetupLocationInput): Promise<void>;
    uploadVerification(licenseProof: ExternalBlob | null, idProof: ExternalBlob | null): Promise<void>;
}
import type { ActivityLogEntry as _ActivityLogEntry, EmergencyLookupResult as _EmergencyLookupResult, EmergencyProfile as _EmergencyProfile, EventType as _EventType, ExternalBlob as _ExternalBlob, MeetupLocation as _MeetupLocation, Place as _Place, PlaceCategory as _PlaceCategory, Route as _Route, SOSSnapshot as _SOSSnapshot, Time as _Time, UserAccountDetails as _UserAccountDetails, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addPlace(arg0: string, arg1: PlaceCategory, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPlace(arg0, to_candid_PlaceCategory_n8(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPlace(arg0, to_candid_PlaceCategory_n8(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createOrUpdateEmergencyProfile(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrUpdateEmergencyProfile(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrUpdateEmergencyProfile(arg0, arg1, arg2);
            return result;
        }
    }
    async createRoute(arg0: string, arg1: string, arg2: Array<string>, arg3: Time, arg4: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createRoute(arg0, arg1, arg2, arg3, to_candid_opt_n12(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRoute(arg0, arg1, arg2, arg3, to_candid_opt_n12(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async createSOSSnapshot(arg0: number, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createSOSSnapshot(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSOSSnapshot(arg0, arg1);
            return result;
        }
    }
    async deactivateMeetupLocation(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deactivateMeetupLocation();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deactivateMeetupLocation();
            return result;
        }
    }
    async emergencyLookup(arg0: Principal, arg1: string): Promise<EmergencyLookupResult> {
        if (this.processError) {
            try {
                const result = await this.actor.emergencyLookup(arg0, arg1);
                return from_candid_EmergencyLookupResult_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.emergencyLookup(arg0, arg1);
            return from_candid_EmergencyLookupResult_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getActivityLogs(): Promise<Array<ActivityLogEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivityLogs();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivityLogs();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllActiveMeetupLocations(): Promise<Array<MeetupLocation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllActiveMeetupLocations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllActiveMeetupLocations();
            return result;
        }
    }
    async getAllAvailableMeetupLocations(): Promise<Array<MeetupLocation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAvailableMeetupLocations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAvailableMeetupLocations();
            return result;
        }
    }
    async getAllLatestSOSLocations(): Promise<Array<SOSSnapshot>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLatestSOSLocations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLatestSOSLocations();
            return result;
        }
    }
    async getAllMembers(): Promise<Array<MemberSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMembers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMembers();
            return result;
        }
    }
    async getAllUserProfiles(): Promise<Array<[Principal, UserProfile]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserProfiles();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserProfiles();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLatestMeetupLocation(arg0: Principal): Promise<MeetupLocation | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLatestMeetupLocation(arg0);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLatestMeetupLocation(arg0);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLatestSOSLocation(arg0: Principal): Promise<SOSSnapshot | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLatestSOSLocation(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLatestSOSLocation(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMeetupLocation(arg0: Principal): Promise<MeetupLocation | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMeetupLocation(arg0);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMeetupLocation(arg0);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRoutes(arg0: Principal): Promise<Array<Route>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoutes(arg0);
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoutes(arg0);
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserAccountDetails(arg0: Principal): Promise<UserAccountDetails> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserAccountDetails(arg0);
                return from_candid_UserAccountDetails_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserAccountDetails(arg0);
            return from_candid_UserAccountDetails_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async reviewVerification(arg0: Principal, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.reviewVerification(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reviewVerification(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n43(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n43(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async searchPlaces(arg0: PlaceCategory | null): Promise<Array<Place>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchPlaces(to_candid_opt_n46(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchPlaces(to_candid_opt_n46(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async shareMeetupLocation(arg0: MeetupLocationInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.shareMeetupLocation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.shareMeetupLocation(arg0);
            return result;
        }
    }
    async updateMeetupLocation(arg0: MeetupLocationInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMeetupLocation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMeetupLocation(arg0);
            return result;
        }
    }
    async uploadVerification(arg0: ExternalBlob | null, arg1: ExternalBlob | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadVerification(await to_candid_opt_n47(this._uploadFile, this._downloadFile, arg0), await to_candid_opt_n47(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadVerification(await to_candid_opt_n47(this._uploadFile, this._downloadFile, arg0), await to_candid_opt_n47(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_ActivityLogEntry_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ActivityLogEntry): ActivityLogEntry {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_EmergencyLookupResult_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EmergencyLookupResult): EmergencyLookupResult {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_EventType_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EventType): EventType {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_PlaceCategory_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlaceCategory): PlaceCategory {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function from_candid_Place_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Place): Place {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_Route_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Route): Route {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
async function from_candid_UserAccountDetails_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserAccountDetails): Promise<UserAccountDetails> {
    return await from_candid_record_n37(_uploadFile, _downloadFile, value);
}
async function from_candid_UserProfile_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): Promise<UserProfile> {
    return await from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SOSSnapshot]): SOSSnapshot | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_EmergencyProfile]): EmergencyProfile | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n28(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): Promise<UserProfile | null> {
    return value.length === 0 ? null : await from_candid_UserProfile_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MeetupLocation]): MeetupLocation | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sosSnapshot: [] | [_SOSSnapshot];
    userName: [] | [string];
    emergencyProfile: [] | [_EmergencyProfile];
}): {
    sosSnapshot?: SOSSnapshot;
    userName?: string;
    emergencyProfile?: EmergencyProfile;
} {
    return {
        sosSnapshot: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.sosSnapshot)),
        userName: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.userName)),
        emergencyProfile: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.emergencyProfile))
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    description: string;
    timestamp: _Time;
    initiatedBy: Principal;
    eventType: _EventType;
}): {
    description: string;
    timestamp: Time;
    initiatedBy: Principal;
    eventType: EventType;
} {
    return {
        description: value.description,
        timestamp: value.timestamp,
        initiatedBy: value.initiatedBy,
        eventType: from_candid_EventType_n21(_uploadFile, _downloadFile, value.eventType)
    };
}
async function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    licenseProof: [] | [_ExternalBlob];
    name: string;
    idProof: [] | [_ExternalBlob];
    isVerified: boolean;
    registrationTime: _Time;
}): Promise<{
    licenseProof?: ExternalBlob;
    name: string;
    idProof?: ExternalBlob;
    isVerified: boolean;
    registrationTime: Time;
}> {
    return {
        licenseProof: record_opt_to_undefined(await from_candid_opt_n27(_uploadFile, _downloadFile, value.licenseProof)),
        name: value.name,
        idProof: record_opt_to_undefined(await from_candid_opt_n27(_uploadFile, _downloadFile, value.idProof)),
        isVerified: value.isVerified,
        registrationTime: value.registrationTime
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    creator: Principal;
    destination: string;
    waypoints: Array<string>;
    start: string;
    notes: [] | [string];
    dateTime: _Time;
}): {
    creator: Principal;
    destination: string;
    waypoints: Array<string>;
    start: string;
    notes?: string;
    dateTime: Time;
} {
    return {
        creator: value.creator,
        destination: value.destination,
        waypoints: value.waypoints,
        start: value.start,
        notes: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.notes)),
        dateTime: value.dateTime
    };
}
async function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    recentRoutes: Array<_Route>;
    emergencyProfile: [] | [_EmergencyProfile];
    accountCreated: _Time;
    activityLog: Array<_ActivityLogEntry>;
    placesAdded: Array<_Place>;
    lastLocations: Array<_MeetupLocation>;
    profile: _UserProfile;
}): Promise<{
    recentRoutes: Array<Route>;
    emergencyProfile?: EmergencyProfile;
    accountCreated: Time;
    activityLog: Array<ActivityLogEntry>;
    placesAdded: Array<Place>;
    lastLocations: Array<MeetupLocation>;
    profile: UserProfile;
}> {
    return {
        recentRoutes: from_candid_vec_n33(_uploadFile, _downloadFile, value.recentRoutes),
        emergencyProfile: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.emergencyProfile)),
        accountCreated: value.accountCreated,
        activityLog: from_candid_vec_n18(_uploadFile, _downloadFile, value.activityLog),
        placesAdded: from_candid_vec_n38(_uploadFile, _downloadFile, value.placesAdded),
        lastLocations: value.lastLocations,
        profile: await from_candid_UserProfile_n25(_uploadFile, _downloadFile, value.profile)
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    submittedBy: Principal;
    description: string;
    category: _PlaceCategory;
    location: string;
}): {
    name: string;
    submittedBy: Principal;
    description: string;
    category: PlaceCategory;
    location: string;
} {
    return {
        name: value.name,
        submittedBy: value.submittedBy,
        description: value.description,
        category: from_candid_PlaceCategory_n41(_uploadFile, _downloadFile, value.category),
        location: value.location
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
async function from_candid_tuple_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, _UserProfile]): Promise<[Principal, UserProfile]> {
    return [
        value[0],
        await from_candid_UserProfile_n25(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sosSnapshot: null;
} | {
    routeCreated: null;
} | {
    meetupLocationUpdated: null;
} | {
    verificationSubmitted: null;
} | {
    meetupLocationShared: null;
} | {
    adminAction: null;
} | {
    emergencyProfileUpdated: null;
} | {
    verificationReviewed: null;
} | {
    userRegistration: null;
} | {
    placeAdded: null;
}): EventType {
    return "sosSnapshot" in value ? EventType.sosSnapshot : "routeCreated" in value ? EventType.routeCreated : "meetupLocationUpdated" in value ? EventType.meetupLocationUpdated : "verificationSubmitted" in value ? EventType.verificationSubmitted : "meetupLocationShared" in value ? EventType.meetupLocationShared : "adminAction" in value ? EventType.adminAction : "emergencyProfileUpdated" in value ? EventType.emergencyProfileUpdated : "verificationReviewed" in value ? EventType.verificationReviewed : "userRegistration" in value ? EventType.userRegistration : "placeAdded" in value ? EventType.placeAdded : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    gasStation: null;
} | {
    hotel: null;
} | {
    shop: null;
} | {
    mechanic: null;
} | {
    restaurant: null;
}): PlaceCategory {
    return "gasStation" in value ? PlaceCategory.gasStation : "hotel" in value ? PlaceCategory.hotel : "shop" in value ? PlaceCategory.shop : "mechanic" in value ? PlaceCategory.mechanic : "restaurant" in value ? PlaceCategory.restaurant : value;
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ActivityLogEntry>): Array<ActivityLogEntry> {
    return value.map((x)=>from_candid_ActivityLogEntry_n19(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, _UserProfile]>): Promise<Array<[Principal, UserProfile]>> {
    return await Promise.all(value.map(async (x)=>await from_candid_tuple_n24(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Route>): Array<Route> {
    return value.map((x)=>from_candid_Route_n34(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Place>): Array<Place> {
    return value.map((x)=>from_candid_Place_n39(_uploadFile, _downloadFile, x));
}
async function to_candid_ExternalBlob_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_PlaceCategory_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlaceCategory): _PlaceCategory {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
async function to_candid_UserProfile_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): Promise<_UserProfile> {
    return await to_candid_record_n44(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlaceCategory | null): [] | [_PlaceCategory] {
    return value === null ? candid_none() : candid_some(to_candid_PlaceCategory_n8(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n45(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    licenseProof?: ExternalBlob;
    name: string;
    idProof?: ExternalBlob;
    isVerified: boolean;
    registrationTime: Time;
}): Promise<{
    licenseProof: [] | [_ExternalBlob];
    name: string;
    idProof: [] | [_ExternalBlob];
    isVerified: boolean;
    registrationTime: _Time;
}> {
    return {
        licenseProof: value.licenseProof ? candid_some(await to_candid_ExternalBlob_n45(_uploadFile, _downloadFile, value.licenseProof)) : candid_none(),
        name: value.name,
        idProof: value.idProof ? candid_some(await to_candid_ExternalBlob_n45(_uploadFile, _downloadFile, value.idProof)) : candid_none(),
        isVerified: value.isVerified,
        registrationTime: value.registrationTime
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlaceCategory): {
    gasStation: null;
} | {
    hotel: null;
} | {
    shop: null;
} | {
    mechanic: null;
} | {
    restaurant: null;
} {
    return value == PlaceCategory.gasStation ? {
        gasStation: null
    } : value == PlaceCategory.hotel ? {
        hotel: null
    } : value == PlaceCategory.shop ? {
        shop: null
    } : value == PlaceCategory.mechanic ? {
        mechanic: null
    } : value == PlaceCategory.restaurant ? {
        restaurant: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
